title: Evan Pratten - Donations
description: >- # this means to ignore newlines until "baseurl:"
  Donations landing page
baseurl: ""
url: "https://donate.retrylife.ca"

btc_address: 17KJxyTZvB36jpcRLjF7KsrwLVt4P6UKRh
xlm_address: GBBUKCQQULS3TLGPKLHIFN2YZUAOTCZHW7ON7CFFJIY5QPFBWGYVA2YQ
paypal_id: RUM9HWMTMQKL4

# Build settings
plugins:
  - jekyll-redirect-from
  - jemoji
  - jekyll-seo-tag
